import {
  Zap,
  Users,
  MousePointerClick,
  Shield,
  Layers,
  Radio,
  ShieldAlert,
  AlertTriangle,
  Eye,
} from "lucide-react";

export default function BelowFold() {
  return (
    <>
      {/* Features */}
      <section className="lazy-section mx-auto max-w-5xl px-6 py-16">
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {[
            { icon: Zap, title: "Instant Sync", desc: "Changes propagate to all users in milliseconds via Supabase Realtime." },
            { icon: MousePointerClick, title: "Drag & Drop", desc: "Reorder cards and columns with smooth DnD Kit animations." },
            { icon: Users, title: "Live Presence", desc: "See who's online and watching your board in real time." },
            { icon: Shield, title: "Role-Based", desc: "Owner, editor, and viewer roles with RLS enforcement." },
          ].map((f) => (
            <div key={f.title} className="float-card rounded-xl p-5">
              <f.icon className="mb-3 h-5 w-5 text-[hsl(var(--primary))]" />
              <h2 className="text-sm font-semibold text-[hsl(var(--foreground))]">{f.title}</h2>
              <p className="mt-1.5 text-[13px] leading-relaxed text-[hsl(var(--muted-foreground))]">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* How It Works */}
      <section className="lazy-section mx-auto max-w-4xl px-6 py-16">
        <h2 className="mb-10 text-center text-2xl font-bold tracking-tight sm:text-3xl">
          How it works
        </h2>
        <div className="grid gap-8 sm:grid-cols-3">
          {[
            { step: "01", icon: Layers, title: "Create a Board", desc: "Start a new Kanban board with customizable columns." },
            { step: "02", icon: Users, title: "Invite Your Team", desc: "Share a link and assign roles to collaborators." },
            { step: "03", icon: Radio, title: "Collaborate Live", desc: "Drag cards, add tasks, and see changes in real time." },
          ].map((s) => (
            <div key={s.step} className="text-center">
              <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))]">
                <s.icon className="h-5 w-5 text-[hsl(var(--primary))]" />
              </div>
              <span className="font-[family-name:var(--font-jetbrains-mono)] text-xs text-[hsl(var(--primary))]">{s.step}</span>
              <h3 className="mt-1 font-semibold text-[hsl(var(--foreground))]">{s.title}</h3>
              <p className="mt-1.5 text-sm text-[hsl(var(--muted-foreground))]">{s.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Built with AI */}
      <section className="lazy-section mx-auto max-w-4xl px-6 py-16">
        <div className="mb-10 text-center">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Built with AI, reviewed by a human
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-[hsl(var(--muted-foreground))]">
            This project was generated by AI agents, but every critical flaw below
            was caught and fixed through my experience directing AI workflows.
          </p>
        </div>

        <div className="space-y-3">
          {[
            {
              type: "critical" as const,
              title: "RLS privilege escalation in board membership",
              desc: "The collab_board_members INSERT policy allowed any user to add themselves as owner to any board. I replaced it with a SECURITY DEFINER RPC that atomically creates board + membership + columns.",
            },
            {
              type: "critical" as const,
              title: "SECURITY DEFINER RPCs without authorization checks",
              desc: "collab_reorder_cards and collab_reorder_columns ran as DB owner with no membership validation. I added collab_is_editor() checks inside each function.",
            },
            {
              type: "critical" as const,
              title: "Auth callback open redirect vulnerability",
              desc: "The /auth/callback route accepted any URL in the next parameter, allowing redirects to malicious sites. I added origin validation to reject external URLs.",
            },
            {
              type: "warning" as const,
              title: "Sequential DB updates on every drag-and-drop",
              desc: "Card reordering fired individual UPDATE queries in a loop. Moving one card across 10 siblings meant 10 round trips. I replaced this with batch RPCs that update all positions in a single transaction.",
            },
            {
              type: "warning" as const,
              title: "Optimistic rollback used stale state snapshot",
              desc: "The snapshot for rollback was taken after handleDragOver mutated state, so failures would rollback to an already-modified state. I moved the snapshot to handleDragStart.",
            },
            {
              type: "warning" as const,
              title: "JSON.stringify on JSONB parameter broke all card moves",
              desc: "The RPC calls passed JSON.stringify(updates) to a JSONB parameter, causing double-serialization. PostgreSQL received a string literal instead of a JSON array, failing on every card move.",
            },
          ].map((item) => (
            <div
              key={item.title}
              className={`rounded-2xl border p-5 ${
                item.type === "critical"
                  ? "border-red-500/20 bg-red-500/[0.04]"
                  : "border-amber-500/20 bg-amber-500/[0.04]"
              }`}
            >
              <div className="flex items-start gap-3">
                {item.type === "critical" ? (
                  <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-400" />
                ) : (
                  <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-400" />
                )}
                <div>
                  <div className="flex items-center gap-2">
                    <span
                      className={`rounded-md px-2 py-0.5 font-[family-name:var(--font-jetbrains-mono)] text-xs font-semibold ${
                        item.type === "critical"
                          ? "bg-red-500/10 text-red-400"
                          : "bg-amber-500/10 text-amber-400"
                      }`}
                    >
                      {item.type === "critical" ? "CRITICAL" : "WARNING"}
                    </span>
                    <h3 className="font-semibold text-[hsl(var(--foreground))]">
                      {item.title}
                    </h3>
                  </div>
                  <p className="mt-1.5 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">
                    {item.desc}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-6 float-card rounded-2xl p-6">
          <div className="flex items-start gap-3">
            <Eye className="mt-0.5 h-5 w-5 shrink-0 text-[hsl(var(--primary))]" />
            <div>
              <h3 className="font-semibold text-[hsl(var(--foreground))]">Why this matters</h3>
              <p className="mt-1.5 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">
                AI code generation is powerful, but it consistently produces plausible-looking code
                with subtle security holes. Across 2 review cycles, I identified and fixed 4 critical
                security vulnerabilities, 12 architectural warnings, and multiple convention issues.
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
