"use client";

import { useState } from "react";
import Link from "next/link";
import { Navbar } from "@/components/navbar";
import { ShortenForm } from "@/components/shorten-form";
import { UrlResult } from "@/components/url-result";
import { Link2, BarChart3, Zap, Code2, ArrowRight, ShieldAlert, AlertTriangle, Eye } from "lucide-react";

interface ShortenResult {
  shortUrl: string;
  slug: string;
  originalUrl: string;
  qrSvg: string;
}

export default function Home() {
  const [result, setResult] = useState<ShortenResult | null>(null);

  return (
    <>
      <Navbar />
      <div className="mx-auto max-w-2xl px-6 py-24">
        <div className="text-center">
          <div className="mx-auto mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-[hsl(var(--primary))]/10">
            <Link2 className="h-8 w-8 text-[hsl(var(--primary))]" />
          </div>
          <h1 className="text-4xl font-bold tracking-tight text-[hsl(var(--foreground))] sm:text-5xl">
            Shorten your links
          </h1>
          <p className="mt-4 text-lg text-[hsl(var(--muted-foreground))]">
            Create short URLs, track clicks, and analyze your traffic.
            <br />
            Free, fast, and open source.
          </p>
        </div>

        <div className="mt-12 space-y-6">
          <ShortenForm onResult={setResult} />
          {result && (
            <UrlResult
              shortUrl={result.shortUrl}
              originalUrl={result.originalUrl}
              qrSvg={result.qrSvg}
            />
          )}
        </div>

        <div className="mt-16 rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--primary))]/5 p-8 text-center">
          <h2 className="text-xl font-semibold text-[hsl(var(--foreground))]">
            Want to see detailed analytics?
          </h2>
          <p className="mt-2 text-[hsl(var(--muted-foreground))]">
            Create a free account to track every click with charts, country breakdowns, device stats, and more.
          </p>
          <Link
            href="/auth/signup"
            className="mt-4 inline-flex items-center gap-2 rounded-lg bg-[hsl(var(--primary))] px-6 py-2.5 text-sm font-medium text-[hsl(var(--primary-foreground))] transition-colors hover:bg-[hsl(var(--primary))]/90"
          >
            Create free account
            <ArrowRight className="h-4 w-4" />
          </Link>
        </div>

        <div className="mt-8 grid gap-6 sm:grid-cols-3">
          <div className="rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 text-center">
            <Zap className="mx-auto h-8 w-8 text-[hsl(var(--primary))]" />
            <p className="mt-3 font-[family-name:var(--font-mono)] text-xl font-bold text-[hsl(var(--foreground))]">
              Fast
            </p>
            <p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">
              Redis-cached redirects in ~5ms
            </p>
          </div>
          <div className="rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 text-center">
            <BarChart3 className="mx-auto h-8 w-8 text-[hsl(var(--primary))]" />
            <p className="mt-3 font-[family-name:var(--font-mono)] text-xl font-bold text-[hsl(var(--foreground))]">
              Analytics
            </p>
            <p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">
              Track clicks, countries, devices &amp; browsers
            </p>
          </div>
          <div className="rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 text-center">
            <Code2 className="mx-auto h-8 w-8 text-[hsl(var(--primary))]" />
            <p className="mt-3 font-[family-name:var(--font-mono)] text-xl font-bold text-[hsl(var(--foreground))]">
              API
            </p>
            <p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">
              Documented REST API + QR codes
            </p>
          </div>
        </div>

        <div className="mt-16">
          <div className="mb-8 text-center">
            <h2 className="text-2xl font-bold text-[hsl(var(--foreground))] sm:text-3xl">
              Built with AI, reviewed by a human
            </h2>
            <p className="mt-3 text-[hsl(var(--muted-foreground))]">
              This project was generated by AI agents, but every critical flaw below was caught
              and fixed through my experience directing AI workflows. Without human oversight,
              these issues would have shipped to production.
            </p>
          </div>

          <div className="space-y-4">
            <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-5">
              <div className="flex items-start gap-3">
                <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-500" />
                <div>
                  <div className="flex items-center gap-2">
                    <span className="rounded bg-red-500/10 px-2 py-0.5 font-[family-name:var(--font-mono)] text-xs font-semibold text-red-500">
                      CRITICAL
                    </span>
                    <h3 className="font-semibold text-[hsl(var(--foreground))]">
                      RLS policies allowed full URL enumeration
                    </h3>
                  </div>
                  <p className="mt-1.5 text-sm text-[hsl(var(--muted-foreground))]">
                    The AI generated a <code className="rounded bg-[hsl(var(--muted))]/50 px-1 font-[family-name:var(--font-mono)] text-xs">SELECT USING (true)</code> policy
                    on <code className="rounded bg-[hsl(var(--muted))]/50 px-1 font-[family-name:var(--font-mono)] text-xs">short_urls</code>,
                    letting any anonymous user query every URL in the database. I restricted the policy
                    to only allow owners and anonymous URLs, and moved the redirect handler to use the
                    service_role client that bypasses RLS.
                  </p>
                </div>
              </div>
            </div>

            <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-5">
              <div className="flex items-start gap-3">
                <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-500" />
                <div>
                  <div className="flex items-center gap-2">
                    <span className="rounded bg-red-500/10 px-2 py-0.5 font-[family-name:var(--font-mono)] text-xs font-semibold text-red-500">
                      CRITICAL
                    </span>
                    <h3 className="font-semibold text-[hsl(var(--foreground))]">
                      Click injection via open INSERT policy
                    </h3>
                  </div>
                  <p className="mt-1.5 text-sm text-[hsl(var(--muted-foreground))]">
                    The <code className="rounded bg-[hsl(var(--muted))]/50 px-1 font-[family-name:var(--font-mono)] text-xs">short_clicks</code> table
                    had <code className="rounded bg-[hsl(var(--muted))]/50 px-1 font-[family-name:var(--font-mono)] text-xs">INSERT WITH CHECK (true)</code>,
                    allowing anyone to inject fake analytics data through the Supabase API. I removed the
                    policy entirely &mdash; click tracking now runs server-side via service_role, which bypasses RLS.
                  </p>
                </div>
              </div>
            </div>

            <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-5">
              <div className="flex items-start gap-3">
                <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-500" />
                <div>
                  <div className="flex items-center gap-2">
                    <span className="rounded bg-red-500/10 px-2 py-0.5 font-[family-name:var(--font-mono)] text-xs font-semibold text-red-500">
                      CRITICAL
                    </span>
                    <h3 className="font-semibold text-[hsl(var(--foreground))]">
                      RPC function callable by anonymous users
                    </h3>
                  </div>
                  <p className="mt-1.5 text-sm text-[hsl(var(--muted-foreground))]">
                    The <code className="rounded bg-[hsl(var(--muted))]/50 px-1 font-[family-name:var(--font-mono)] text-xs">increment_click_count</code> function
                    was a <code className="rounded bg-[hsl(var(--muted))]/50 px-1 font-[family-name:var(--font-mono)] text-xs">SECURITY DEFINER</code> function
                    exposed to <code className="rounded bg-[hsl(var(--muted))]/50 px-1 font-[family-name:var(--font-mono)] text-xs">anon</code> and <code className="rounded bg-[hsl(var(--muted))]/50 px-1 font-[family-name:var(--font-mono)] text-xs">public</code> roles,
                    letting anyone inflate click counts via the REST API. I added <code className="rounded bg-[hsl(var(--muted))]/50 px-1 font-[family-name:var(--font-mono)] text-xs">REVOKE EXECUTE FROM public, anon, authenticated</code> and
                    set a fixed <code className="rounded bg-[hsl(var(--muted))]/50 px-1 font-[family-name:var(--font-mono)] text-xs">search_path</code> to prevent schema injection.
                  </p>
                </div>
              </div>
            </div>

            <div className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-5">
              <div className="flex items-start gap-3">
                <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-yellow-500" />
                <div>
                  <div className="flex items-center gap-2">
                    <span className="rounded bg-yellow-500/10 px-2 py-0.5 font-[family-name:var(--font-mono)] text-xs font-semibold text-yellow-500">
                      WARNING
                    </span>
                    <h3 className="font-semibold text-[hsl(var(--foreground))]">
                      301 redirects broke analytics and URL management
                    </h3>
                  </div>
                  <p className="mt-1.5 text-sm text-[hsl(var(--muted-foreground))]">
                    The AI used 301 (permanent) redirects, causing browsers to cache the destination forever.
                    Users could never update or delete a short URL, and repeat visits would never be tracked.
                    I changed to 302 (temporary) redirects so every click hits the server and is recorded.
                  </p>
                </div>
              </div>
            </div>

            <div className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-5">
              <div className="flex items-start gap-3">
                <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-yellow-500" />
                <div>
                  <div className="flex items-center gap-2">
                    <span className="rounded bg-yellow-500/10 px-2 py-0.5 font-[family-name:var(--font-mono)] text-xs font-semibold text-yellow-500">
                      WARNING
                    </span>
                    <h3 className="font-semibold text-[hsl(var(--foreground))]">
                      Synchronous click tracking added ~200ms latency
                    </h3>
                  </div>
                  <p className="mt-1.5 text-sm text-[hsl(var(--muted-foreground))]">
                    Click analytics were recorded before sending the redirect response, adding
                    database write latency to every click. I moved tracking to Next.js
                    {" "}<code className="rounded bg-[hsl(var(--muted))]/50 px-1 font-[family-name:var(--font-mono)] text-xs">after()</code> API,
                    which runs asynchronously after the response is sent &mdash; redirects now complete in ~5ms.
                  </p>
                </div>
              </div>
            </div>

            <div className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-5">
              <div className="flex items-start gap-3">
                <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-yellow-500" />
                <div>
                  <div className="flex items-center gap-2">
                    <span className="rounded bg-yellow-500/10 px-2 py-0.5 font-[family-name:var(--font-mono)] text-xs font-semibold text-yellow-500">
                      WARNING
                    </span>
                    <h3 className="font-semibold text-[hsl(var(--foreground))]">
                      user_id spoofing on URL creation
                    </h3>
                  </div>
                  <p className="mt-1.5 text-sm text-[hsl(var(--muted-foreground))]">
                    The INSERT policy used <code className="rounded bg-[hsl(var(--muted))]/50 px-1 font-[family-name:var(--font-mono)] text-xs">WITH CHECK (true)</code>,
                    allowing any authenticated user to set an arbitrary <code className="rounded bg-[hsl(var(--muted))]/50 px-1 font-[family-name:var(--font-mono)] text-xs">user_id</code> and
                    claim ownership of URLs created by others. I tightened the policy
                    to <code className="rounded bg-[hsl(var(--muted))]/50 px-1 font-[family-name:var(--font-mono)] text-xs">WITH CHECK (user_id IS NULL OR user_id = auth.uid())</code>.
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-8 rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6">
            <div className="flex items-start gap-3">
              <Eye className="mt-0.5 h-5 w-5 shrink-0 text-[hsl(var(--primary))]" />
              <div>
                <h3 className="font-semibold text-[hsl(var(--foreground))]">
                  Why this matters
                </h3>
                <p className="mt-1.5 text-sm text-[hsl(var(--muted-foreground))]">
                  AI code generation is powerful, but it consistently produces plausible-looking code with
                  subtle security holes and architectural mistakes. Across 4 review cycles, I identified
                  and fixed 3 critical security vulnerabilities, 8 architectural warnings, and multiple
                  convention issues &mdash; none of which the AI caught on its own. Effective AI-assisted
                  development requires someone who knows what to look for.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
