import Link from "next/link";
import { ProductGrid } from "@/components/product-grid";
import {
  ArrowRight,
  ShieldAlert,
  AlertTriangle,
  Eye,
} from "lucide-react";
import type { Product } from "@/lib/types";

interface BelowFoldProps {
  products: Product[];
}

export default function BelowFold({ products }: BelowFoldProps) {
  return (
    <>
      {/* Featured Products */}
      <section className="lazy-section mx-auto max-w-6xl px-6 py-16">
        <div className="flex items-center justify-between">
          <h2 className="text-2xl font-bold tracking-tight">Featured Products</h2>
          <Link
            href="/products"
            className="flex items-center gap-1 text-sm font-medium text-[hsl(var(--primary))] transition-colors hover:brightness-110"
          >
            View all
            <ArrowRight className="h-3.5 w-3.5" />
          </Link>
        </div>
        <div className="mt-8">
          <ProductGrid products={products} />
        </div>
      </section>

      {/* Built with AI */}
      <section className="lazy-section mx-auto max-w-4xl px-6 py-16">
        <div className="mb-10 text-center">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Built with AI, reviewed by a human
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-[hsl(var(--muted-foreground))]">
            This project was generated by AI agents, but every critical flaw below
            was caught and fixed through my experience directing AI workflows.
          </p>
        </div>

        <div className="space-y-3">
          {[
            {
              type: "critical" as const,
              title: "RLS policies allowed admin privilege escalation",
              desc: "The AI generated RLS policies on shop_profiles without restricting the role column, letting any user self-promote to admin. I added explicit AND role = 'customer' constraints.",
            },
            {
              type: "critical" as const,
              title: "Non-transactional webhook handler could corrupt orders",
              desc: "The Stripe webhook handler had separate sequential queries without a transaction. If the order insert failed after stock was decremented, inventory would be permanently lost. I replaced it with an atomic PL/pgSQL function.",
            },
            {
              type: "critical" as const,
              title: "Seed route granted admin role without authorization",
              desc: "The /api/seed route set the calling user as admin with no guard. I implemented a bootstrap guard where only the first user becomes admin, plus rate limiting.",
            },
            {
              type: "critical" as const,
              title: "Missing Stripe client packages would break checkout",
              desc: "The AI planned Embedded Checkout but never added @stripe/stripe-js or @stripe/react-stripe-js to dependencies. The build would have failed at the checkout page.",
            },
            {
              type: "warning" as const,
              title: "No webhook idempotency — duplicate orders on retry",
              desc: "Stripe can send the same checkout.session.completed event multiple times. I added a UNIQUE constraint on stripe_checkout_session_id and a check-before-insert guard.",
            },
            {
              type: "warning" as const,
              title: "Redis KEYS scan would block the server at scale",
              desc: "The AI used redis.keys('shop:*') for cache invalidation — an O(N) blocking command. I replaced it with a version-key counter pattern for O(1) invalidation.",
            },
            {
              type: "warning" as const,
              title: "No stock validation before checkout",
              desc: "Users could purchase out-of-stock items. I added pre-checkout validation plus atomic stock decrement with a FOR UPDATE row lock to prevent overselling.",
            },
          ].map((item) => (
            <div
              key={item.title}
              className={`rounded-xl border p-5 ${
                item.type === "critical"
                  ? "border-red-500/20 bg-red-500/[0.04]"
                  : "border-amber-500/20 bg-amber-500/[0.04]"
              }`}
            >
              <div className="flex items-start gap-3">
                {item.type === "critical" ? (
                  <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-400" />
                ) : (
                  <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-400" />
                )}
                <div>
                  <div className="flex items-center gap-2">
                    <span
                      className={`rounded-md px-2 py-0.5 font-[family-name:var(--font-jetbrains-mono)] text-xs font-semibold ${
                        item.type === "critical"
                          ? "bg-red-500/10 text-red-400"
                          : "bg-amber-500/10 text-amber-400"
                      }`}
                    >
                      {item.type === "critical" ? "CRITICAL" : "WARNING"}
                    </span>
                    <h3 className="font-semibold text-[hsl(var(--foreground))]">
                      {item.title}
                    </h3>
                  </div>
                  <p className="mt-1.5 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">
                    {item.desc}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-6 luxury-card rounded-xl p-6">
          <div className="flex items-start gap-3">
            <Eye className="mt-0.5 h-5 w-5 shrink-0 text-[hsl(var(--primary))]" />
            <div>
              <h3 className="font-semibold text-[hsl(var(--foreground))]">Why this matters</h3>
              <p className="mt-1.5 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">
                AI code generation is powerful, but it consistently produces plausible-looking code
                with subtle security holes. Across 3 review cycles, I identified and fixed 4 critical
                security vulnerabilities, 26 architectural warnings, and 12 convention issues.
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
