import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { BoardCard } from "@/components/board-card";
import { CreateBoardForm } from "@/components/create-board-form";
import { Kanban, ShieldAlert, AlertTriangle, Eye } from "lucide-react";

export default async function BoardsPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) redirect("/auth/login");

  const { data: memberships } = await supabase
    .from("collab_board_members")
    .select("board_id, role, collab_boards(id, title, description, updated_at)")
    .eq("user_id", user.id)
    .order("joined_at", { ascending: false });

  const boards = (memberships ?? []).map((m) => {
    const board = m.collab_boards as unknown as {
      id: string;
      title: string;
      description: string;
      updated_at: string;
    };
    return {
      id: board.id,
      title: board.title,
      description: board.description,
      role: m.role,
      updatedAt: board.updated_at,
    };
  });

  // Get member counts
  const boardIds = boards.map((b) => b.id);
  const { data: memberCounts } = await supabase
    .from("collab_board_members")
    .select("board_id")
    .in("board_id", boardIds.length > 0 ? boardIds : ["none"]);

  const countMap: Record<string, number> = {};
  (memberCounts ?? []).forEach((m) => {
    countMap[m.board_id] = (countMap[m.board_id] || 0) + 1;
  });

  return (
    <main className="mx-auto max-w-6xl px-4 py-8">
      <div className="mb-8 flex items-center gap-3">
        <Kanban className="h-7 w-7 text-primary" />
        <h1 className="text-3xl font-bold">My Boards</h1>
      </div>

      {boards.length > 0 ? (
        <div className="mb-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {boards.map((board) => (
            <BoardCard
              key={board.id}
              id={board.id}
              title={board.title}
              description={board.description}
              role={board.role}
              memberCount={countMap[board.id] || 1}
              updatedAt={board.updatedAt}
            />
          ))}
        </div>
      ) : (
        <p className="mb-8 text-muted-foreground">You don&apos;t have any boards yet. Create one below!</p>
      )}

      <CreateBoardForm />

      <div className="mt-16">
        <div className="mb-8 text-center">
          <h2 className="text-2xl font-bold sm:text-3xl">
            Built with AI, reviewed by a human
          </h2>
          <p className="mt-3 text-muted-foreground">
            This project was generated by AI agents, but every critical flaw below was caught
            and fixed through my experience directing AI workflows. Without human oversight,
            these issues would have shipped to production.
          </p>
        </div>

        <div className="space-y-4">
          <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-5">
            <div className="flex items-start gap-3">
              <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-red-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-red-500">
                    CRITICAL
                  </span>
                  <h3 className="font-semibold">
                    RLS privilege escalation in board membership
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The <code className="rounded bg-muted/50 px-1 font-mono text-xs">collab_board_members</code> INSERT
                  policy allowed any authenticated user to add themselves as <code className="rounded bg-muted/50 px-1 font-mono text-xs">owner</code> to
                  any board. I removed the client-side insert path entirely and created
                  a <code className="rounded bg-muted/50 px-1 font-mono text-xs">collab_create_board</code> SECURITY DEFINER
                  RPC that atomically creates the board + owner membership + default columns.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-5">
            <div className="flex items-start gap-3">
              <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-red-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-red-500">
                    CRITICAL
                  </span>
                  <h3 className="font-semibold">
                    SECURITY DEFINER RPCs without authorization checks
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The <code className="rounded bg-muted/50 px-1 font-mono text-xs">collab_reorder_cards</code> and <code className="rounded bg-muted/50 px-1 font-mono text-xs">collab_reorder_columns</code> functions
                  ran as the DB owner with no membership validation &mdash; any authenticated user could reorder cards
                  on any board. I added <code className="rounded bg-muted/50 px-1 font-mono text-xs">collab_is_editor(auth.uid(), board_id)</code> checks
                  inside each function and revoked public execution.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-5">
            <div className="flex items-start gap-3">
              <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-red-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-red-500">
                    CRITICAL
                  </span>
                  <h3 className="font-semibold">
                    Auth callback open redirect vulnerability
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The <code className="rounded bg-muted/50 px-1 font-mono text-xs">/auth/callback</code> route accepted
                  any URL in the <code className="rounded bg-muted/50 px-1 font-mono text-xs">next</code> parameter, allowing attackers to redirect
                  users to malicious sites after login. I added origin validation to reject external URLs.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-5">
            <div className="flex items-start gap-3">
              <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-yellow-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-yellow-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-yellow-500">
                    WARNING
                  </span>
                  <h3 className="font-semibold">
                    Sequential DB updates on every drag-and-drop
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  Card reordering fired individual UPDATE queries in a loop &mdash; moving one card across 10 siblings meant
                  10 round trips. I replaced this with batch RPCs (<code className="rounded bg-muted/50 px-1 font-mono text-xs">collab_reorder_cards</code>)
                  that update all positions in a single transaction.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-5">
            <div className="flex items-start gap-3">
              <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-yellow-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-yellow-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-yellow-500">
                    WARNING
                  </span>
                  <h3 className="font-semibold">
                    Optimistic rollback used stale state snapshot
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The snapshot for rollback was taken after <code className="rounded bg-muted/50 px-1 font-mono text-xs">handleDragOver</code> mutated
                  state, so failures would &ldquo;rollback&rdquo; to an already-modified state.
                  I moved the snapshot to <code className="rounded bg-muted/50 px-1 font-mono text-xs">handleDragStart</code> to capture the true pre-drag state.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-5">
            <div className="flex items-start gap-3">
              <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-yellow-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-yellow-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-yellow-500">
                    WARNING
                  </span>
                  <h3 className="font-semibold">
                    JSON.stringify on JSONB parameter broke all card moves
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The RPC calls passed <code className="rounded bg-muted/50 px-1 font-mono text-xs">JSON.stringify(updates)</code> to
                  a <code className="rounded bg-muted/50 px-1 font-mono text-xs">JSONB</code> parameter, causing double-serialization. PostgreSQL
                  received a string literal instead of a JSON array, making <code className="rounded bg-muted/50 px-1 font-mono text-xs">jsonb_array_elements()</code> fail
                  on every card move. I removed the redundant stringify &mdash; the Supabase client handles serialization.
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-8 rounded-xl border bg-card p-6">
          <div className="flex items-start gap-3">
            <Eye className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
            <div>
              <h3 className="font-semibold">
                Why this matters
              </h3>
              <p className="mt-1.5 text-sm text-muted-foreground">
                AI code generation is powerful, but it consistently produces plausible-looking code with
                subtle security holes and architectural mistakes. Across 2 review cycles, I identified
                and fixed 4 critical security vulnerabilities, 12 architectural warnings, and multiple
                convention issues &mdash; none of which the AI caught on its own. Effective AI-assisted
                development requires someone who knows what to look for.
              </p>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
