import { ShieldAlert, AlertTriangle, Eye } from "lucide-react";

const reviewItems = [
  {
    type: "critical",
    title: "SECURITY DEFINER functions without search_path isolation",
    desc: "All RLS helper functions lacked SET search_path = '', allowing schema injection attacks. I added search_path isolation, REVOKE EXECUTE FROM PUBLIC, and qualified all table references.",
  },
  {
    type: "critical",
    title: "Workspace creation allowed user impersonation",
    desc: "The saas_create_workspace RPC accepted a p_user_id from the client, letting any user create workspaces on behalf of another. I removed the parameter — the function now uses auth.uid() internally.",
  },
  {
    type: "critical",
    title: "Open redirect vulnerability in auth callback",
    desc: "The /auth/callback route blindly redirected to whatever ?next= parameter was supplied. I added strict validation: must start with /, not //, and not contain ://.",
  },
  {
    type: "critical",
    title: "Issue number race condition under concurrency",
    desc: "Issue numbers used MAX(issue_number) + 1, allowing duplicate numbers. I redesigned it with pg_advisory_xact_lock and a UNIQUE constraint as safety net.",
  },
  {
    type: "warning",
    title: "FOR ALL policies silently blocked member SELECT access",
    desc: "FOR ALL policies with admin-only checks blocked regular members from viewing projects. I split into per-command policies with correct permission scoping.",
  },
  {
    type: "warning",
    title: "Stripe webhook didn't invalidate Redis plan cache",
    desc: "After checkout, the old plan stayed in Redis for up to 2 minutes, causing 'limit reached' errors post-upgrade. I added explicit redis.del() calls in every webhook handler.",
  },
  {
    type: "warning",
    title: "Cross-workspace data injection via mutable issue_id",
    desc: "Comment UPDATE policy didn't prevent changing issue_id after creation, allowing cross-workspace data injection. I added a BEFORE UPDATE trigger that prevents issue_id modification.",
  },
] as const;

export function LandingReview() {
  return (
    <section className="lazy-section mx-auto max-w-4xl px-6 py-16">
      <div className="mb-10">
        <h2 className="text-2xl font-bold tracking-tight sm:text-3xl">
          Built with AI, reviewed by a human
        </h2>
        <p className="mt-3 max-w-xl text-sm text-[hsl(var(--muted-foreground))]">
          This project was generated by AI agents across 9 adversarial review
          cycles. Every critical flaw below was caught and fixed through my
          experience directing AI workflows.
        </p>
      </div>

      <div className="space-y-2">
        {reviewItems.map((item) => (
          <div
            key={item.title}
            className={`rounded-lg border p-4 ${
              item.type === "critical"
                ? "border-red-500/15 bg-red-500/[0.03]"
                : "border-amber-500/15 bg-amber-500/[0.03]"
            }`}
          >
            <div className="flex items-start gap-3">
              {item.type === "critical" ? (
                <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-red-400" />
              ) : (
                <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-400" />
              )}
              <div>
                <div className="flex items-center gap-2">
                  <span
                    className={`rounded px-1.5 py-0.5 font-[family-name:var(--font-jetbrains-mono)] text-[10px] font-semibold uppercase ${
                      item.type === "critical"
                        ? "bg-red-500/10 text-red-400"
                        : "bg-amber-500/10 text-amber-400"
                    }`}
                  >
                    {item.type}
                  </span>
                  <h3 className="text-sm font-medium text-[hsl(var(--foreground))]">
                    {item.title}
                  </h3>
                </div>
                <p className="mt-1 text-[13px] leading-relaxed text-[hsl(var(--muted-foreground))]">
                  {item.desc}
                </p>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-6 noir-card rounded-lg p-5">
        <div className="flex items-start gap-3">
          <Eye className="mt-0.5 h-4 w-4 shrink-0 text-[hsl(var(--primary))]" />
          <div>
            <h3 className="text-sm font-medium text-[hsl(var(--foreground))]">
              Why this matters
            </h3>
            <p className="mt-1 text-[13px] leading-relaxed text-[hsl(var(--muted-foreground))]">
              Multi-tenant SaaS apps amplify the consequences of every flaw:
              a single RLS issue can expose every customer&apos;s data. Across 9
              adversarial review cycles, I identified and fixed 4 critical
              security vulnerabilities and 3 architectural warnings.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
