import { resolveWorkspaceSlug } from "@/lib/ensure-workspace";
import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import { Bug, FolderKanban, Users, Activity, CheckCircle, Clock, ShieldAlert, AlertTriangle, Eye } from "lucide-react";

export default async function WorkspaceDashboard({
  params,
}: {
  params: Promise<{ workspace: string }>;
}) {
  const { workspace: slug } = await params;
  const workspace = await resolveWorkspaceSlug(slug);
  if (!workspace) notFound();

  const supabase = await createClient();

  const [issuesRes, projectsRes, membersRes, recentRes, doneRes] = await Promise.all([
    supabase
      .from("saas_issues")
      .select("*", { count: "exact", head: true })
      .eq("workspace_id", workspace.id)
      .not("status", "in", '("done","cancelled")'),
    supabase
      .from("saas_projects")
      .select("*", { count: "exact", head: true })
      .eq("workspace_id", workspace.id),
    supabase
      .from("saas_members")
      .select("*", { count: "exact", head: true })
      .eq("workspace_id", workspace.id),
    supabase
      .from("saas_activities")
      .select("action, created_at, metadata")
      .eq("workspace_id", workspace.id)
      .order("created_at", { ascending: false })
      .limit(5),
    supabase
      .from("saas_issues")
      .select("*", { count: "exact", head: true })
      .eq("workspace_id", workspace.id)
      .eq("status", "done"),
  ]);

  const openIssues = issuesRes.count ?? 0;
  const totalProjects = projectsRes.count ?? 0;
  const totalMembers = membersRes.count ?? 0;
  const doneIssues = doneRes.count ?? 0;
  const recentActivities = recentRes.data ?? [];

  return (
    <div className="flex-1 space-y-6 p-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">{workspace.name}</h1>
        <p className="text-muted-foreground">
          Workspace overview and recent activity
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <div className="rounded-lg border bg-card p-6">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Bug className="h-4 w-4" />
            Open Issues
          </div>
          <p className="mt-2 text-3xl font-bold">{openIssues}</p>
        </div>
        <div className="rounded-lg border bg-card p-6">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <CheckCircle className="h-4 w-4" />
            Completed
          </div>
          <p className="mt-2 text-3xl font-bold">{doneIssues}</p>
        </div>
        <div className="rounded-lg border bg-card p-6">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <FolderKanban className="h-4 w-4" />
            Projects
          </div>
          <p className="mt-2 text-3xl font-bold">{totalProjects}</p>
        </div>
        <div className="rounded-lg border bg-card p-6">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Users className="h-4 w-4" />
            Members
          </div>
          <p className="mt-2 text-3xl font-bold">{totalMembers}</p>
        </div>
      </div>

      <div className="rounded-lg border bg-card p-6">
        <div className="flex items-center gap-2 mb-4">
          <Activity className="h-5 w-5 text-muted-foreground" />
          <h2 className="text-lg font-semibold">Recent Activity</h2>
        </div>
        {recentActivities.length === 0 ? (
          <p className="text-sm text-muted-foreground">No recent activity</p>
        ) : (
          <div className="space-y-3">
            {recentActivities.map((activity, i) => (
              <div key={i} className="flex items-center gap-3">
                <Clock className="h-3.5 w-3.5 text-muted-foreground shrink-0" />
                <span className="text-sm">
                  {activity.action.replace(/_/g, " ")}
                  {(activity.metadata as Record<string, unknown>)?.title && (
                    <span className="font-medium">
                      {" "}&quot;{String((activity.metadata as Record<string, unknown>).title)}&quot;
                    </span>
                  )}
                </span>
              </div>
            ))}
          </div>
        )}
      </div>

      <div>
        <div className="mb-6 text-center">
          <h2 className="text-2xl font-bold tracking-tight">
            Built with AI, reviewed by a human
          </h2>
          <p className="mt-3 text-muted-foreground max-w-2xl mx-auto">
            This project was generated by AI agents across 9 adversarial review cycles.
            Every critical flaw below was caught and fixed through my experience directing
            AI workflows. Without human oversight, these issues would have shipped to production.
          </p>
        </div>

        <div className="space-y-4">
          <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-5">
            <div className="flex items-start gap-3">
              <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-red-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-red-500">
                    CRITICAL
                  </span>
                  <h3 className="font-semibold">
                    SECURITY DEFINER functions without search_path isolation
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The AI generated all RLS helper functions (<code className="rounded bg-muted/50 px-1 font-mono text-xs">saas_is_member</code>,{" "}
                  <code className="rounded bg-muted/50 px-1 font-mono text-xs">saas_is_admin</code>) as{" "}
                  <code className="rounded bg-muted/50 px-1 font-mono text-xs">SECURITY DEFINER</code> without{" "}
                  <code className="rounded bg-muted/50 px-1 font-mono text-xs">SET search_path = &apos;&apos;</code>,
                  allowing an attacker to create a malicious schema with shadow tables that the function would resolve first.
                  I added explicit <code className="rounded bg-muted/50 px-1 font-mono text-xs">search_path</code> isolation,{" "}
                  <code className="rounded bg-muted/50 px-1 font-mono text-xs">REVOKE EXECUTE FROM PUBLIC</code>, and
                  qualified all table references with <code className="rounded bg-muted/50 px-1 font-mono text-xs">public.</code> prefix.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-5">
            <div className="flex items-start gap-3">
              <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-red-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-red-500">
                    CRITICAL
                  </span>
                  <h3 className="font-semibold">
                    Workspace creation allowed user impersonation
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The <code className="rounded bg-muted/50 px-1 font-mono text-xs">saas_create_workspace</code> RPC
                  accepted a <code className="rounded bg-muted/50 px-1 font-mono text-xs">p_user_id</code> parameter from the client,
                  letting any authenticated user create workspaces on behalf of another user and become their owner.
                  I removed the parameter entirely &mdash; the function now uses{" "}
                  <code className="rounded bg-muted/50 px-1 font-mono text-xs">auth.uid()</code> internally,
                  making impersonation impossible.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-5">
            <div className="flex items-start gap-3">
              <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-red-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-red-500">
                    CRITICAL
                  </span>
                  <h3 className="font-semibold">
                    Open redirect vulnerability in auth callback
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The <code className="rounded bg-muted/50 px-1 font-mono text-xs">/auth/callback</code> route
                  blindly redirected to whatever <code className="rounded bg-muted/50 px-1 font-mono text-xs">?next=</code> parameter
                  was supplied, enabling phishing attacks via URLs like{" "}
                  <code className="rounded bg-muted/50 px-1 font-mono text-xs">?next=//evil.com</code>. I added
                  strict validation: the redirect must start with <code className="rounded bg-muted/50 px-1 font-mono text-xs">/</code>,
                  must not start with <code className="rounded bg-muted/50 px-1 font-mono text-xs">//</code>,
                  and must not contain <code className="rounded bg-muted/50 px-1 font-mono text-xs">://</code>.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-5">
            <div className="flex items-start gap-3">
              <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-red-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-red-500">
                    CRITICAL
                  </span>
                  <h3 className="font-semibold">
                    Issue number race condition under concurrency
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The AI generated issue numbers with a simple{" "}
                  <code className="rounded bg-muted/50 px-1 font-mono text-xs">MAX(issue_number) + 1</code> query
                  as a standalone RPC, allowing two simultaneous requests to read the same max and produce duplicate numbers.
                  I redesigned it as an atomic function using{" "}
                  <code className="rounded bg-muted/50 px-1 font-mono text-xs">pg_advisory_xact_lock</code> to
                  serialize access per-project, with a <code className="rounded bg-muted/50 px-1 font-mono text-xs">UNIQUE(project_id, issue_number)</code> constraint as safety net.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-5">
            <div className="flex items-start gap-3">
              <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-yellow-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-yellow-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-yellow-500">
                    WARNING
                  </span>
                  <h3 className="font-semibold">
                    FOR ALL policies silently blocked member SELECT access
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The AI used <code className="rounded bg-muted/50 px-1 font-mono text-xs">FOR ALL</code> policies
                  with admin-only checks on <code className="rounded bg-muted/50 px-1 font-mono text-xs">saas_projects</code> and{" "}
                  <code className="rounded bg-muted/50 px-1 font-mono text-xs">saas_members</code>, not knowing that
                  Postgres AND-composes same-command policies. This meant regular members could not even view projects
                  or teammates. I split into explicit per-command policies:{" "}
                  <code className="rounded bg-muted/50 px-1 font-mono text-xs">FOR SELECT</code> with membership check,
                  separate <code className="rounded bg-muted/50 px-1 font-mono text-xs">FOR INSERT/UPDATE/DELETE</code> with admin check.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-5">
            <div className="flex items-start gap-3">
              <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-yellow-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-yellow-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-yellow-500">
                    WARNING
                  </span>
                  <h3 className="font-semibold">
                    Stripe webhook didn&apos;t invalidate Redis plan cache
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  After a successful checkout, the Stripe webhook updated the database but left the old plan
                  in Redis cache (TTL 120s). Users who upgraded would still see free-tier limits for up to 2 minutes,
                  leading to confusing &quot;limit reached&quot; errors immediately after paying. I added explicit{" "}
                  <code className="rounded bg-muted/50 px-1 font-mono text-xs">redis.del(`saas:plan:$&#123;workspaceId&#125;`)</code> calls
                  in every webhook handler path.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-5">
            <div className="flex items-start gap-3">
              <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-yellow-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-yellow-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-yellow-500">
                    WARNING
                  </span>
                  <h3 className="font-semibold">
                    Cross-workspace data injection via mutable issue_id on comments
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The comment UPDATE policy didn&apos;t prevent changing{" "}
                  <code className="rounded bg-muted/50 px-1 font-mono text-xs">issue_id</code> after creation.
                  A malicious user could move their comment from workspace A to an issue in workspace B,
                  bypassing RLS membership checks. I added a{" "}
                  <code className="rounded bg-muted/50 px-1 font-mono text-xs">BEFORE UPDATE</code> trigger
                  that raises an exception if <code className="rounded bg-muted/50 px-1 font-mono text-xs">issue_id</code> is modified.
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-6 rounded-xl border bg-card p-6">
          <div className="flex items-start gap-3">
            <Eye className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
            <div>
              <h3 className="font-semibold">
                Why this matters
              </h3>
              <p className="mt-1.5 text-sm text-muted-foreground">
                AI code generation is powerful, but it consistently produces plausible-looking code with
                subtle security holes and architectural mistakes. In this project alone, I identified
                and fixed 4 critical security vulnerabilities and 3 architectural warnings across
                9 adversarial review cycles &mdash; none of which the AI caught on its own.
                Multi-tenant SaaS apps amplify the consequences: a single RLS flaw can expose
                every customer&apos;s data. Effective AI-assisted development requires someone
                who knows what to look for.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
