import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { getCached } from "@/lib/redis";
import { StoreHeader } from "@/components/store-header";
import { ProductGrid } from "@/components/product-grid";
import { Button } from "@/components/ui/button";
import { ArrowRight, ShieldAlert, AlertTriangle, Eye } from "lucide-react";
import type { Product } from "@/lib/types";

async function getFeaturedProducts(): Promise<Product[]> {
  return getCached("shop:products:featured", 60, async () => {
    const supabase = await createClient();
    const { data } = await supabase
      .from("shop_products")
      .select("*, category:shop_categories(id, name, slug)")
      .eq("active", true)
      .order("created_at", { ascending: false })
      .limit(4);
    return (data as Product[]) || [];
  });
}

async function getUser() {
  const supabase = await createClient();
  const { data } = await supabase.auth.getUser();
  return data.user;
}

export default async function HomePage() {
  const [products, user] = await Promise.all([
    getFeaturedProducts(),
    getUser(),
  ]);

  return (
    <div className="min-h-screen">
      <StoreHeader user={user} />

      <section className="relative overflow-hidden border-b">
        <div className="mx-auto max-w-7xl px-4 py-24 sm:px-6 sm:py-32 lg:px-8">
          <div className="mx-auto max-w-2xl text-center">
            <h1 className="text-4xl font-bold tracking-tight sm:text-6xl">
              Welcome to the{" "}
              <span className="text-primary">Shop</span>
            </h1>
            <p className="mt-6 text-lg leading-8 text-muted-foreground">
              A demo e-commerce platform built with Next.js, Supabase, and
              Stripe. Browse products, add to cart, and checkout with a
              complete payment flow.
            </p>
            <div className="mt-10 flex items-center justify-center gap-4">
              <Link href="/products">
                <Button size="lg">
                  Browse Products
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </Link>
            </div>
          </div>
        </div>
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(45%_40%_at_50%_60%,hsl(var(--primary)/0.12),transparent)]" />
      </section>

      <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between">
          <h2 className="text-2xl font-bold tracking-tight">
            Featured Products
          </h2>
          <Link
            href="/products"
            className="text-sm font-medium text-primary hover:underline"
          >
            View all
          </Link>
        </div>
        <div className="mt-8">
          <ProductGrid products={products} />
        </div>
      </section>

      <section className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
        <div className="mb-8 text-center">
          <h2 className="text-2xl font-bold tracking-tight sm:text-3xl">
            Built with AI, reviewed by a human
          </h2>
          <p className="mt-3 text-muted-foreground">
            This project was generated by AI agents, but every critical flaw below was caught
            and fixed through my experience directing AI workflows. Without human oversight,
            these issues would have shipped to production.
          </p>
        </div>

        <div className="space-y-4">
          <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-5">
            <div className="flex items-start gap-3">
              <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-red-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-red-500">
                    CRITICAL
                  </span>
                  <h3 className="font-semibold">
                    RLS policies allowed admin privilege escalation
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The AI generated RLS INSERT/UPDATE policies on <code className="rounded bg-muted/50 px-1 font-mono text-xs">shop_profiles</code> without
                  restricting the <code className="rounded bg-muted/50 px-1 font-mono text-xs">role</code> column, letting any authenticated user
                  self-promote to admin by setting <code className="rounded bg-muted/50 px-1 font-mono text-xs">role = &apos;admin&apos;</code> via the Supabase API.
                  I added explicit <code className="rounded bg-muted/50 px-1 font-mono text-xs">AND role = &apos;customer&apos;</code> constraints and created
                  a <code className="rounded bg-muted/50 px-1 font-mono text-xs">shop_is_admin()</code> SECURITY DEFINER STABLE function for all admin checks.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-5">
            <div className="flex items-start gap-3">
              <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-red-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-red-500">
                    CRITICAL
                  </span>
                  <h3 className="font-semibold">
                    Non-transactional webhook handler could corrupt orders
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The AI wrote the Stripe webhook handler as separate sequential queries &mdash; stock decrement,
                  order creation, and order items &mdash; without a transaction. If the order insert failed after
                  stock was decremented, inventory would be permanently lost. I replaced it with
                  a <code className="rounded bg-muted/50 px-1 font-mono text-xs">shop_create_order()</code> PL/pgSQL SECURITY DEFINER function
                  that handles everything atomically with automatic rollback on failure.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-5">
            <div className="flex items-start gap-3">
              <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-red-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-red-500">
                    CRITICAL
                  </span>
                  <h3 className="font-semibold">
                    Seed route granted admin role without authorization
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The <code className="rounded bg-muted/50 px-1 font-mono text-xs">/api/seed</code> route set the calling user as admin with no
                  guard, meaning any authenticated user who discovered the endpoint could become admin.
                  I implemented a bootstrap guard where only the first user becomes admin, and subsequent
                  calls require existing admin role, plus added rate limiting and origin checking.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-5">
            <div className="flex items-start gap-3">
              <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-red-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-red-500">
                    CRITICAL
                  </span>
                  <h3 className="font-semibold">
                    Missing Stripe client packages would break checkout
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The AI planned Embedded Checkout with <code className="rounded bg-muted/50 px-1 font-mono text-xs">EmbeddedCheckoutProvider</code> but
                  never added <code className="rounded bg-muted/50 px-1 font-mono text-xs">@stripe/stripe-js</code> or <code className="rounded bg-muted/50 px-1 font-mono text-xs">@stripe/react-stripe-js</code> to
                  the dependency list. The build would have failed at the checkout page. I caught this during
                  dependency review and added both packages before execution.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-5">
            <div className="flex items-start gap-3">
              <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-yellow-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-yellow-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-yellow-500">
                    WARNING
                  </span>
                  <h3 className="font-semibold">
                    No webhook idempotency &mdash; duplicate orders on retry
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  Stripe can send the same <code className="rounded bg-muted/50 px-1 font-mono text-xs">checkout.session.completed</code> event
                  multiple times. The AI had no deduplication logic, so each retry would create a new order
                  and decrement stock again. I added a UNIQUE constraint
                  on <code className="rounded bg-muted/50 px-1 font-mono text-xs">stripe_checkout_session_id</code> and a check-before-insert guard
                  in the webhook handler.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-5">
            <div className="flex items-start gap-3">
              <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-yellow-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-yellow-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-yellow-500">
                    WARNING
                  </span>
                  <h3 className="font-semibold">
                    Redis KEYS scan would block the server at scale
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The AI used <code className="rounded bg-muted/50 px-1 font-mono text-xs">redis.keys(&quot;shop:*&quot;)</code> for cache invalidation,
                  which is an O(N) blocking command that scans every key in the database. On a production
                  Redis instance this would freeze all connections. I replaced it with a version-key counter
                  pattern (<code className="rounded bg-muted/50 px-1 font-mono text-xs">INCR shop:cache:version</code>) for O(1) non-blocking invalidation.
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-yellow-500/30 bg-yellow-500/5 p-5">
            <div className="flex items-start gap-3">
              <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-yellow-500" />
              <div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-yellow-500/10 px-2 py-0.5 font-mono text-xs font-semibold text-yellow-500">
                    WARNING
                  </span>
                  <h3 className="font-semibold">
                    No stock validation before checkout
                  </h3>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">
                  The AI created the checkout flow without validating product stock or active status,
                  allowing users to purchase out-of-stock or deactivated items. I added pre-checkout validation
                  that checks stock levels and product status, plus atomic stock decrement with
                  a <code className="rounded bg-muted/50 px-1 font-mono text-xs">FOR UPDATE</code> row lock inside the database function to prevent overselling under concurrency.
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-8 rounded-xl border bg-card p-6">
          <div className="flex items-start gap-3">
            <Eye className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
            <div>
              <h3 className="font-semibold">
                Why this matters
              </h3>
              <p className="mt-1.5 text-sm text-muted-foreground">
                AI code generation is powerful, but it consistently produces plausible-looking code with
                subtle security holes and architectural mistakes. Across 3 review cycles, I identified
                and fixed 4 critical security vulnerabilities, 26 architectural warnings, and 12
                convention issues &mdash; none of which the AI caught on its own. Effective AI-assisted
                development requires someone who knows what to look for.
              </p>
            </div>
          </div>
        </div>
      </section>

      <footer className="border-t">
        <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
          <p className="text-center text-sm text-muted-foreground">
            Built by Caio Silva &middot; Next.js &middot; Supabase &middot;
            Stripe &middot; Tailwind CSS
          </p>
        </div>
      </footer>
    </div>
  );
}
